version: '3.5'

services:
  test_postgres:
    container_name: test_postgres
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./test-db-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/dbdata
      - POSTGRES_PORT=${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  db_backuper:
    build: .
    container_name: db_backuper
    command: sh -c "chmod +x ./entry.sh ./main.py && ./entry.sh"
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - DB_USER_NAME=${POSTGRES_USER}

volumes:
  test-db-postgres-data:
